
version: '3'

services:
  app:
    build: .
    image: yotin/app:1.0.0
    container_name: TCT_32_APP
    ports:
      - ${APP_PORTS}
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_SSL=${DATABASE_SSL}
  db:
    image: postgres:latest
    container_name: TCT_32_DB
    ports:
       - ${DB_PORTS}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}


  